site_name: Lichess

repo_name: 2022.2-Lichess
repo_url: https://github.com/Requisitos-de-Software/2022.2-Lichess

copyright: Copyright &copy; 2022 Lichess

theme:
  name: material
  language: pt
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Tema claro
  font:
    text: "Inter"
    code: "sans-serif"

  features:
    - tabs
    - navigation.section

nav:
  - Sobre o Projeto: index.md
  - Atas:
      - 01/11/2022: atas/ata_01_11.md
      - 10/11/2022: atas/ata_10_11.md
      - 15/11/2022: atas/ata_15_11.md
      - 22/11/2022: atas/ata_22_11.md
      - 29/11/2022: atas/ata_29_11.md
      - 06/12/2022: atas/ata_06_12.md
      - 13/12/2022: atas/ata_13_12.md
      - 20/12/2022: "atas/ata_20_12.md"
      - 03/01/2023: atas/ata_03_01_2023.md
      - 18/01/2023: atas/ata_18_01.md
      - 25/01/2023: atas/ata_25_01.md
  - Planejamento:
      - Aplicativo Selecionado: planejamento/aplicativo_selecionado.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Realizado: planejamento/cronograma_realizado.md
      - Metodologias: planejamento/metodologias.md
  - Pré-Rastreabilidade:
      - Rich-Picture: prerastreabilidade/richpicture.md
  - Elicitacão:
      - Técnicas Planejadas: elicitacao/tecnicas_planejadas.md
      - Brainstorming: elicitacao/brainstorming.md
      - Glossário: elicitacao/glossario.md
      - Introspecção: elicitacao/introspeccao.md
      - Questionário: elicitacao/questionario.md
      - Personas: elicitacao/personas.md
      - Storytelling: elicitacao/storytelling.md
      - Entrevista: elicitacao/entrevista.md
      - Priorização: elicitacao/priorizacao.md
  - Modelagem:
      - Léxico: modelagem/lexico.md
      - NFR: modelagem/nfr_framework.md
      - Casos de uso: modelagem/casos_de_uso.md
      - Cenários: modelagem/cenarios.md
      - Especificação Suplementar: modelagem/especificacao_suplementar.md
      - Modelagem Ágil:
          - Histórias de Usuário: modelagem/agil/us.md
          - Backlog: modelagem/agil/backlog.md
  - Análise de Requisitos (V&V):
      - Planejamento da Verificação: analise-grupo2/planejamento.md
      - Verificação:
          - Rich-picture: analise-grupo2/richpicture.md
          - Léxicos: analise-grupo2/lexicos.md
          - Brainstorming: analise-grupo2/brainstorming.md
          - Glossário: analise-grupo2/glossario.md
          - Introspecção: analise-grupo2/introspeccao.md
          - Questionario: analise-grupo2/questionario.md
          - Personas: analise-grupo2/personas.md
          - Storytelling: analise-grupo2/storytelling.md
          - Entrevista: analise-grupo2/entrevista.md
          - Priorização: analise-grupo2/priorizacao.md
          - NFR Framework: analise-grupo2/nfr.md
          - Casos de Uso: analise-grupo2/casos-de-uso.md
          - Cenários: analise-grupo2/cenarios.md
          - Especificação Suplementar: analise-grupo2/especificacao-suplementar.md
          - Histórias de Usuário: analise-grupo2/historias-de-usuario.md
          - Backlog: analise-grupo2/backlog.md
      - Validação:
          - Comunicação Informal: analise-grupo2/validacao/comprovacao_informal.md
      - Teste Piloto - V&V Grupo 3:
          - Verificação:
              - NFR Framework: analise-grupo3/verificacao/nfr-framework.md
              - Casos de Uso: analise-grupo3/verificacao/casos-de-uso.md
              - Brainstorm: analise-grupo3/verificacao/brainstorm.md
              - Backlog: analise-grupo3/verificacao/backlog.md
              - Léxico: analise-grupo3/verificacao/lexico.md
              - Histórias de Usuário: analise-grupo3/verificacao/historias-de-usuario.md
              - Técnicas de elicitação: analise-grupo3/verificacao/tecnicas-de-elicitacao.md
              - Priorização: analise-grupo3/verificacao/priorizacao.md
              - Especificação Suplementar: analise-grupo3/verificacao/especificacao_sup.md
              - Cenários: analise-grupo3/verificacao/cenarios.md
              - Entrevista: analise-grupo3/verificacao/entrevista.md
              - Perfil do Usuário: analise-grupo3/verificacao/perfil-usuario.md
              - Personas: analise-grupo3/verificacao/persona.md
              - Introspecção: analise-grupo3/verificacao/introspeccao.md
          - Validação:
              - Comunicação Informal: analise-grupo3/validacao/comunicacao.md
  - Pós-rastreabilidade:
      - Forward-from: posrastreabilidade/forward_from.md
      - Backward-from: posrastreabilidade/backward.md
  - Apresentações: apresentacoes.md
