site_name: Grupo 2
site_url: https://requisitos-de-software.github.io/2022.2-Grupo2/

nav:
  - Home: index.md
  - Equipe: equipe.md
  - Atas:
    - Primeiro Encontro - 01/11/2022: atas/ata_01_11.md
  - "Planejamento":
    - "Cronograma": "planejamento/cronograma.md"
  # - "Nova navegação": "nome do arquivo relativo a docs"
  # - "Nova navegação":
  #   - "Navegação com filhos": "nome do arquivo relativo a docs"
    